### PR TITLE
Fedora 38 and Spark 3.2.4

### PR DESCRIPTION
**Pull request by akrause2014**
Deployment to Fedora 38 with Python 3.11 and Spark 3.2.4

### CODE REVIEW

**Review by Zarquan — COMMENTED** [review]
Why did you create a separate config file for this ?
* Using a separate config file means that all the changes to the module versions are untested with the existing config file - so merging this  branch could break the existing build.
* Using a separate config file means that unless other people explicitly change their build process, this will not be used.

**Comment by akrause2014** [comment]
Happy to merge the config file. That means changing all of them?

**Comment by akrause2014** [comment]
Propose to implement #1243 and keep only `zeppelin-54.86-spark-6.26.43.yml` (with merged changes) as part of this.

**Comment by Zarquan** [comment]
Update the one used in our current deployment notes, `zeppelin-54.86-spark-6.26.43`
https://github.com/wfau/gaia-dmp/blob/f978640542872e16a7c112abc00606de23f71b58/notes/instructions/live-deploy.md?plain=1#L32

and we can delete the others #1243.

**Review by stvoutsin — APPROVED** [review]
Looks good

**Pull request merged**
